// Initialize OpenTelemetry before loading any other modules.
require("./instrumentation");

const express = require("express");
const { metrics } = require("@opentelemetry/api");

const app = express();
const PORT = process.env.PORT || 3000;

// Create a test metric
const meter = metrics.getMeter("bluebox-test-app");

const requestCounter = meter.createCounter("bluebox_test_requests", {
  description: "Test requests generated by the Bluebox test application",
});

// Count every request
app.use((req, res, next) => {
  requestCounter.add(1, {
    method: req.method,
    route: req.path,
  });

  next();
});

app.get("/", (req, res) => {
  res.json({
    message: "Bluebox test application is running!",
    timestamp: new Date().toISOString()
  });
});

app.get("/api/users", (req, res) => {
  res.json({
    users: [
      { id: 1, name: "Alice" },
      { id: 2, name: "Bob" }
    ]
  });
});


app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});